### ISSUE TITLE
Umbraco content and user search not working

### ISSUE THREAD

**Issue by colin-tactuum** [Novicell/Novicell.Examine.ElasticSearch#23]
I have installed the latest beta version on an Umbraco 8.16.0 site with just The Starter Kit installed.
Searching for content in Umbraco (top right search) and Umbraco users causes an error.

Here is the stack trace:
System.NotImplementedException: The method or operation is not implemented.
   at Examine.LuceneEngine.Search.LuceneBooleanOperationBase.SelectFields(ISet`1 fieldNames) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Search\\LuceneBooleanOperationBase.cs:line 84
   at Umbraco.Web.Search.UmbracoTreeSearcher.ExamineSearch(String query, UmbracoEntityTypes entityType, Int32 pageSize, Int64 pageIndex, String culture, Int64& totalFound, String searchFrom, Boolean ignoreUserStartNodes) in D:\\a\\1\\s\\src\\Umbraco.Web\\Search\\UmbracoTreeSearcher.cs:line 191
   at Umbraco.Web.Trees.ContentTreeController.Search(String query, Int32 pageSize, Int64 pageIndex, Int64& totalFound, String searchFrom) in D:\\a\\1\\s\\src\\Umbraco.Web\\Trees\\ContentTreeController.cs:line 331
   at Umbraco.Web.Editors.EntityController.SearchAll(String query) in D:\\a\\1\\s\\src\\Umbraco.Web\\Editors\\EntityController.cs:line 152
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by bielu** [comment]
That is related to breaking changes in latest examine version, I will be looking over weekend to resolve that issue.

**Comment by bielu** [comment]
@colin-tactuum I am looking into that issue looks like it simply mismatch of assemblies but I need look little more as that issue is weird :)

**Comment by bielu** [comment]
@colin-tactuum I resolved that issue with that pr https://github.com/Novicell/Novicell.Examine.ElasticSearch/pull/24 , today new version should be release, can you confirm if it does resolve issue for you?

**Comment by bielu** [comment]
@colin-tactuum that is extremely weird, as it working perfectly fine in test project (clear 8.16) 0.o
