### ISSUE TITLE
Indexing fails on Umbraco startup

### ISSUE THREAD

**Issue by brvaland** [Novicell/Novicell.Examine.ElasticSearch#4]
I have discovered indexing fails on umbraco startup. 

Replication Steps
> Delete all indexes from elastic search via index management.
> Recycle application pool
> Browse to umbraco backoffice > setting > examine management,
> Notice error will be displayed.
> Log Viewer also include error message as below.
> Notice indexes name in elastic index (prefix + indexname) missing datetime at the end.

`System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Novicell.Examine.ElasticSearch.Indexers.ElasticSearchBaseIndex.IndexExists()
   at Umbraco.Examine.IndexRebuilder.<>c.<RebuildIndexes>b__7_0(IIndex x) in d:\a\1\s\src\Umbraco.Examine\IndexRebuilder.cs:line 43
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Umbraco.Examine.IndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes) in d:\a\1\s\src\Umbraco.Examine\IndexRebuilder.cs:line 42
   at Umbraco.Web.Search.BackgroundIndexRebuilder.RebuildOnStartupTask.Run() in d:\a\1\s\src\Umbraco.Web\Search\BackgroundIndexRebuilder.cs:line 93`

**Comment by bielu** [comment]
The issue was resolved and shouldn't appear any more
